//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public System.Guid Id { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> City { get; set; }
        public Nullable<System.Guid> District { get; set; }
        public string Phone { get; set; }
    }
}
