using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portal.Core.Util
{
    public class MailContent
    {
        public static string ConfirmEmailContent = "<table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" style=\"background-color:#ffffff\">"
                                        +"      <tbody><tr>"
                                        +"        <td align=\"center\">"
                                        +"          <div style=\"max-width:558px;margin-top:0;margin-right:auto;margin-bottom:0;margin-left:auto;padding-top:0;padding-right:10px;padding-bottom:0;padding-left:10px\">"
                                        +"            <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:558px;padding-bottom:0;padding-right:0;padding-top:0;padding-left:0;margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#444444\">"
                                        +"              <tbody><tr>"
                                        +"                <td valign=\"top\" width=\"100%\" style=\"padding-left:0;padding-bottom:18px;padding-right:0;padding-top:22px;border-collapse:collapse;border-bottom-width:1px;border-bottom-color:#dcdcdc;border-bottom-style:solid\">"
                                        +"                  <img src=\"http://zody.vn/Images/logo.png\" alt=\"ZODY\" title=\"ZODY\" width=\"130\" border=\"0\" style=\"display:block\" class=\"CToWUd\"> "
                                        +"                </td>"
                                        +"              </tr>"
                                        +"              <tr>"
                                        +"                <td width=\"100%\" style=\"padding-top:44px;padding-right:0;padding-bottom:0;padding-left:0\">"
                                        +"                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" style=\"font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#444444;background-color:#ffffff;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;margin-left:0;margin-bottom:0;margin-top:0;margin-right:0\">"
                                        +"                    <tbody><tr>"
                                        +"                      <td valign=\"top\" width=\"100%\" style=\"font-family:Arial,Helvetica,sans-serif;font-size:18px;line-height:32px;color:#039be5;font-weight:500\">"
                                        +"                        HỆ THỐNG VIỆC LÀM VÀ TUYỂN DỤNG TRỰC TUYẾN - ZODY"						
                                        +"                      </td>"
                                        +"                    </tr>"
                                        +"                    <tr>"
                                        +"                      <td width=\"100%\">"
                                        +"                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">"
                                        +"                          <tbody><tr>"
                                        +"                            <td valign=\"top\" width=\"100%\" style=\"padding-left:0;padding-bottom:5px;padding-right:0;padding-top:5px;font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#333333\">"
                                        +"                              <p>"
                                        +"                                <br/>"
                                        +"                              </p>"
                                        +"                              <p>"
                                        +"                                Cám ơn bạn đã đăng ký gia nhập vào <strong>Hệ thống Việc làm và Tuyển dụng trực tuyến ZODY</strong>. Bạn chỉ cần thực hiện 1 thao tác nữa để hoàn tất quá trình đăng ký."
                                        +"                              </p>"
                                        +"                              <p>"
                                        +"                                Nếu thực sự bạn không tạo tài khoản trên hệ thống của ZODY xin hãy bỏ qua email này."
                                        +"                              </p>"
                                        +"								<p>"
                                        +"                                Bạn vui lòng click vào liên kết dưới đây để xác nhận đăng ký:"
                                        +"                              <p>"
                                        +"                                Link xác nhận: [LINK]"
                                        +"                              </p>"
                                        +"							  <p>"
                                        +"							  Nếu bạn vẫn gặp vấn đề về đăng nhập, vui lòng liên hệ với chúng tôi tại: team@zody.vn"
                                        +"							  </p>"
                                        +"                              <p>"                           
                                        +"								Trân trọng cám ơn!"
                                        +"								<br>"
                                        +"								<strong>Quản lý thành viên đăng ký hệ thống ZODY</strong>" 
                                        +"                              </p>"                            
                                        +"                            </td>"
                                        +"                          </tr>"
                                        +"                        </tbody></table>"
                                        +"                      </td>"
                                        +"                    </tr>"
                                        +"                  </tbody></table>"
                                        +"                </td>"
                                        +"              </tr>"
                                        +"            </tbody></table>"
                                        +"          </div>"
                                        +"        </td>"
                                        +"      </tr>"      
                                        +"    </tbody></table>";
        public static string ResetEmailContent = "<table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" style=\"background-color:#ffffff\">"
                                        + "      <tbody><tr>"
                                        + "        <td align=\"center\">"
                                        + "          <div style=\"max-width:558px;margin-top:0;margin-right:auto;margin-bottom:0;margin-left:auto;padding-top:0;padding-right:10px;padding-bottom:0;padding-left:10px\">"
                                        + "            <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:558px;padding-bottom:0;padding-right:0;padding-top:0;padding-left:0;margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#444444\">"
                                        + "              <tbody><tr>"
                                        + "                <td valign=\"top\" width=\"100%\" style=\"padding-left:0;padding-bottom:18px;padding-right:0;padding-top:22px;border-collapse:collapse;border-bottom-width:1px;border-bottom-color:#dcdcdc;border-bottom-style:solid\">"
                                        + "                  <img src=\"http://zody.vn/Images/logo.png\" alt=\"ZODY\" title=\"ZODY\" width=\"130\" border=\"0\" style=\"display:block\" class=\"CToWUd\"> "
                                        + "                </td>"
                                        + "              </tr>"
                                        + "              <tr>"
                                        + "                <td width=\"100%\" style=\"padding-top:44px;padding-right:0;padding-bottom:0;padding-left:0\">"
                                        + "                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" style=\"font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#444444;background-color:#ffffff;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;margin-left:0;margin-bottom:0;margin-top:0;margin-right:0\">"
                                        + "                    <tbody><tr>"
                                        + "                      <td valign=\"top\" width=\"100%\" style=\"font-family:Arial,Helvetica,sans-serif;font-size:18px;line-height:32px;color:#039be5;font-weight:500\">"
                                        + "                        HỆ THỐNG VIỆC LÀM VÀ TUYỂN DỤNG TRỰC TUYẾN - ZODY"
                                        + "                      </td>"
                                        + "                    </tr>"
                                        + "                    <tr>"
                                        + "                      <td width=\"100%\">"
                                        + "                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">"
                                        + "                          <tbody><tr>"
                                        + "                            <td valign=\"top\" width=\"100%\" style=\"padding-left:0;padding-bottom:5px;padding-right:0;padding-top:5px;font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#333333\">"
                                        + "                              <p>"
                                        + "                                <br/>"
                                        + "                              </p>"
                                        + "                              <p>"
                                        + "                                Chúng tôi nhận được yêu cầu khởi tạo lại mật khẩu của bạn trên <strong>Hệ thống Việc làm và Tuyển dụng trực tuyến ZODY</strong>, rất có thể vì bạn đã quên mất nó"
                                        + "                              </p>"
                                        + "                              <p>"
                                        + "                                Nếu thực sự bạn không gởi yêu cầu này trên hệ thống của ZODY xin hãy bỏ qua email này."
                                        + "                              </p>"
                                        + "								<p>"
                                        + "                                Để đặt lại mật khẩu, hãy click vào liên kết sau:"
                                        + "                              <p>"
                                        + "                                Link xác nhận: [LINK]"
                                        + "                              </p>"
                                        + "							  <p>"
                                        + "							  Nếu bạn vẫn gặp vấn đề về đăng nhập, vui lòng liên hệ với chúng tôi tại: team@zody.vn"
                                        + "							  </p>"
                                        + "                              <p>"
                                        + "								Trân trọng cám ơn!"
                                        + "								<br>"
                                        + "								<strong>Quản lý thành viên đăng ký hệ thống ZODY</strong>"
                                        + "                              </p>"
                                        + "                            </td>"
                                        + "                          </tr>"
                                        + "                        </tbody></table>"
                                        + "                      </td>"
                                        + "                    </tr>"
                                        + "                  </tbody></table>"
                                        + "                </td>"
                                        + "              </tr>"
                                        + "            </tbody></table>"
                                        + "          </div>"
                                        + "        </td>"
                                        + "      </tr>"
                                        + "    </tbody></table>";
        public static string RegisterSocialEmailContent = "<table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" style=\"background-color:#ffffff\">"
                                        + "      <tbody><tr>"
                                        + "        <td align=\"center\">"
                                        + "          <div style=\"max-width:558px;margin-top:0;margin-right:auto;margin-bottom:0;margin-left:auto;padding-top:0;padding-right:10px;padding-bottom:0;padding-left:10px\">"
                                        + "            <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"max-width:558px;padding-bottom:0;padding-right:0;padding-top:0;padding-left:0;margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#444444\">"
                                        + "              <tbody><tr>"
                                        + "                <td valign=\"top\" width=\"100%\" style=\"padding-left:0;padding-bottom:18px;padding-right:0;padding-top:22px;border-collapse:collapse;border-bottom-width:1px;border-bottom-color:#dcdcdc;border-bottom-style:solid\">"
                                        + "                  <img src=\"http://zody.vn/Images/logo.png\" alt=\"ZODY\" title=\"ZODY\" width=\"130\" border=\"0\" style=\"display:block\" class=\"CToWUd\"> "
                                        + "                </td>"
                                        + "              </tr>"
                                        + "              <tr>"
                                        + "                <td width=\"100%\" style=\"padding-top:44px;padding-right:0;padding-bottom:0;padding-left:0\">"
                                        + "                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" style=\"font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#444444;background-color:#ffffff;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;margin-left:0;margin-bottom:0;margin-top:0;margin-right:0\">"
                                        + "                    <tbody><tr>"
                                        + "                      <td valign=\"top\" width=\"100%\" style=\"font-family:Arial,Helvetica,sans-serif;font-size:18px;line-height:32px;color:#039be5;font-weight:500\">"
                                        + "                        HỆ THỐNG VIỆC LÀM VÀ TUYỂN DỤNG TRỰC TUYẾN - ZODY"
                                        + "                      </td>"
                                        + "                    </tr>"
                                        + "                    <tr>"
                                        + "                      <td width=\"100%\">"
                                        + "                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">"
                                        + "                          <tbody><tr>"
                                        + "                            <td valign=\"top\" width=\"100%\" style=\"padding-left:0;padding-bottom:5px;padding-right:0;padding-top:5px;font-family:Arial,Helvetica,sans-serif;font-weight:normal;font-size:13px;line-height:18px;color:#333333\">"
                                        + "                              <p>"
                                        + "                                <br/>"
                                        + "                              </p>"
                                        + "                              <p>"
                                        + "                                Chúng tôi nhận được yêu cầu khởi tạo lại mật khẩu của bạn trên <strong>Hệ thống Việc làm và Tuyển dụng trực tuyến ZODY</strong>, rất có thể vì bạn đã quên mất nó"
                                        + "                              </p>"
                                        + "                              <p>"
                                        + "                                Nếu thực sự bạn không gởi yêu cầu này trên hệ thống của ZODY xin hãy bỏ qua email này."
                                        + "                              </p>"
                                        + "								<p>"
                                        + "                                Để đặt lại mật khẩu, hãy click vào liên kết sau:"
                                        + "                              <p>"
                                        + "                                Link xác nhận: [LINK]"
                                        + "                              </p>"
                                        + "							  <p>"
                                        + "							  Nếu bạn vẫn gặp vấn đề về đăng nhập, vui lòng liên hệ với chúng tôi tại: team@zody.vn"
                                        + "							  </p>"
                                        + "                              <p>"
                                        + "								Trân trọng cám ơn!"
                                        + "								<br>"
                                        + "								<strong>Quản lý thành viên đăng ký hệ thống ZODY</strong>"
                                        + "                              </p>"
                                        + "                            </td>"
                                        + "                          </tr>"
                                        + "                        </tbody></table>"
                                        + "                      </td>"
                                        + "                    </tr>"
                                        + "                  </tbody></table>"
                                        + "                </td>"
                                        + "              </tr>"
                                        + "            </tbody></table>"
                                        + "          </div>"
                                        + "        </td>"
                                        + "      </tr>"
                                        + "    </tbody></table>";
    }
}